version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
    assignees:
      - "w0rmr1d3r"


  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
    assignees:
      - "w0rmr1d3r"
